// Frases célebres con su autor. Solo frases de autoría conocida y documentada.
var FRASES = [
  ['¿Por qué no te callas?', 'Juan Carlos I', 'Cumbre Iberoamericana de 2007'],
  ['Es el vecino el que elige al alcalde y es el alcalde el que quiere que sean los vecinos el alcalde.', 'Mariano Rajoy', 'Entrevista en 2015'],
  ['Somos sentimientos y tenemos seres humanos.', 'Mariano Rajoy', 'Mitin en 2015'],
  ['It\'s very difficult todo esto.', 'Mariano Rajoy', 'Rueda de prensa en 2015'],
  ['Los catalanes hacen cosas.', 'Mariano Rajoy', 'Discurso en 2015'],
  ['Un vaso es un vaso y un plato es un plato.', 'Mariano Rajoy', 'Discurso en 2015'],
  ['Luis, sé fuerte.', 'Mariano Rajoy', 'Mensaje a Bárcenas publicado en 2013'],
  ['Manda huevos.', 'Federico Trillo', 'Congreso, 1997'],
  ['Váyase, señor González.', 'José María Aznar', 'Congreso, años noventa'],
  ['No es no.', 'Pedro Sánchez', 'Investidura de 2016'],
  ['Puedo prometer y prometo.', 'Adolfo Suárez', 'Campaña de 1977'],
  ['Españoles, Franco ha muerto.', 'Carlos Arias Navarro', 'Televisión, 20 de noviembre de 1975'],
  ['¡Quieto todo el mundo! ¡Se sienten, coño!', 'Antonio Tejero', 'Golpe de Estado del 23F, 1981'],
  ['El que no esté colocado, que se coloque… y al loro.', 'Enrique Tierno Galván', 'Concierto en Madrid, 1984'],
  ['¡Que inventen ellos!', 'Miguel de Unamuno', 'El pórtico del templo, 1906'],
  ['Yo soy yo y mi circunstancia.', 'José Ortega y Gasset', 'Meditaciones del Quijote, 1914'],
  ['En un lugar de la Mancha, de cuyo nombre no quiero acordarme…', 'Miguel de Cervantes', 'Don Quijote, 1605'],
  ['Si me queréis, irse.', 'Lola Flores', 'Boda de su hija, 1987'],
  ['Partido a partido.', 'Diego Pablo Simeone', 'Su lema en el Atlético'],
  ['¿Por qué?', 'José Mourinho', 'Rueda de prensa en 2011'],
  ['Creo que soy un special one.', 'José Mourinho', 'Presentación en el Chelsea, 2004'],
  ['Ganar, y ganar, y ganar, y volver a ganar.', 'Luis Aragonés', 'Selección española, 2008'],
  ['El fútbol es un estado de ánimo.', 'Jorge Valdano', 'Frase célebre'],
  ['Fútbol es fútbol.', 'Vujadin Boškov', 'Entrenador del Real Madrid'],
  ['¡Iniesta de mi vida!', 'José Antonio Camacho', 'Final del Mundial 2010'],
  ['La vida puede ser maravillosa.', 'Andrés Montes', 'Narraciones de baloncesto y fútbol'],
  ['La pelota no se mancha.', 'Diego Armando Maradona', 'Despedida en la Bombonera, 2001'],
  ['Hasta luego, Lucas.', 'Chiquito de la Calzada', 'Humorista'],
  ['¡Fistro pecador de la pradera!', 'Chiquito de la Calzada', 'Humorista'],
  ['Es la economía, estúpido.', 'James Carville', 'Campaña de Bill Clinton, 1992'],
  ['Pienso, luego existo.', 'René Descartes', 'Discurso del método, 1637'],
  ['Solo sé que no sé nada.', 'Sócrates', 'Según Platón'],
  ['Houston, tenemos un problema.', 'Jim Lovell', 'Apolo 13, 1970'],
  ['Un pequeño paso para el hombre, un gran salto para la humanidad.', 'Neil Armstrong', 'Llegada a la Luna, 1969'],
  ['Tengo un sueño.', 'Martin Luther King', 'Washington, 1963'],
  ['Sí, se puede.', 'Barack Obama', 'Campaña de 2008, en inglés'],
  ['Sangre, esfuerzo, lágrimas y sudor.', 'Winston Churchill', 'Cámara de los Comunes, 1940'],
  ['Hasta el infinito y más allá.', 'Buzz Lightyear', 'Toy Story, 1995'],
  ['Que la Fuerza te acompañe.', 'Obi-Wan Kenobi', 'Star Wars'],
  ['Sayonara, baby.', 'Terminator', 'Terminator 2, doblaje en España'],
  ['Me llamo Íñigo Montoya. Tú mataste a mi padre. Prepárate a morir.', 'Íñigo Montoya', 'La princesa prometida, 1987'],
  ['Winter is coming. Se acerca el invierno.', 'Ned Stark', 'Juego de tronos'],
  ['¿Qué pasa, neng?', 'El Neng de Castefa', 'Buenafuente, 2005']
];
