// Frases célebres con su autor. Solo frases de autoría conocida y documentada.
var FRASES = [
  ['¿Por qué no te callas?', 'Juan Carlos I', 'Cumbre Iberoamericana de 2007'],
  ['Es el vecino el que elige al alcalde y es el alcalde el que quiere que sean los vecinos el alcalde.', 'Mariano Rajoy', 'Entrevista en 2015'],
  ['Somos sentimientos y tenemos seres humanos.', 'Mariano Rajoy', 'Mitin en 2015'],
  ['It\'s very difficult todo esto.', 'Mariano Rajoy', 'Rueda de prensa en 2015'],
  ['Los catalanes hacen cosas.', 'Mariano Rajoy', 'Discurso en 2015'],
  ['Un vaso es un vaso y un plato es un plato.', 'Mariano Rajoy', 'Discurso en 2015'],
  ['Luis, sé fuerte.', 'Mariano Rajoy', 'Mensaje a Bárcenas publicado en 2013'],
  ['Manda huevos.', 'Federico Trillo', 'Congreso, 1997'],
  ['Váyase, señor González.', 'José María Aznar', 'Congreso, años noventa'],
  ['No es no.', 'Pedro Sánchez', 'Investidura de 2016'],
  ['Puedo prometer y prometo.', 'Adolfo Suárez', 'Campaña de 1977'],
  ['Españoles, Franco ha muerto.', 'Carlos Arias Navarro', 'Televisión, 20 de noviembre de 1975'],
  ['¡Quieto todo el mundo! ¡Se sienten, coño!', 'Antonio Tejero', 'Golpe de Estado del 23F, 1981'],
  ['El que no esté colocado, que se coloque… y al loro.', 'Enrique Tierno Galván', 'Concierto en Madrid, 1984'],
  ['¡Que inventen ellos!', 'Miguel de Unamuno', 'El pórtico del templo, 1906'],
  ['Yo soy yo y mi circunstancia.', 'José Ortega y Gasset', 'Meditaciones del Quijote, 1914'],
  ['En un lugar de la Mancha, de cuyo nombre no quiero acordarme…', 'Miguel de Cervantes', 'Don Quijote, 1605'],
  ['Si me queréis, irse.', 'Lola Flores', 'Boda de su hija, 1987'],
  ['Partido a partido.', 'Diego Pablo Simeone', 'Su lema en el Atlético'],
  ['¿Por qué?', 'José Mourinho', 'Rueda de prensa en 2011'],
  ['Creo que soy un special one.', 'José Mourinho', 'Presentación en el Chelsea, 2004'],
  ['Ganar, y ganar, y ganar, y volver a ganar.', 'Luis Aragonés', 'Selección española, 2008'],
  ['El fútbol es un estado de ánimo.', 'Jorge Valdano', 'Frase célebre'],
  ['Fútbol es fútbol.', 'Vujadin Boškov', 'Entrenador del Real Madrid'],
  ['¡Iniesta de mi vida!', 'José Antonio Camacho', 'Final del Mundial 2010'],
  ['La vida puede ser maravillosa.', 'Andrés Montes', 'Narraciones de baloncesto y fútbol'],
  ['La pelota no se mancha.', 'Diego Armando Maradona', 'Despedida en la Bombonera, 2001'],
  ['Hasta luego, Lucas.', 'Chiquito de la Calzada', 'Humorista'],
  ['¡Fistro pecador de la pradera!', 'Chiquito de la Calzada', 'Humorista'],
  ['Es la economía, estúpido.', 'James Carville', 'Campaña de Bill Clinton, 1992'],
  ['Pienso, luego existo.', 'René Descartes', 'Discurso del método, 1637'],
  ['Solo sé que no sé nada.', 'Sócrates', 'Según Platón'],
  ['Houston, tenemos un problema.', 'Jim Lovell', 'Apolo 13, 1970'],
  ['Un pequeño paso para el hombre, un gran salto para la humanidad.', 'Neil Armstrong', 'Llegada a la Luna, 1969'],
  ['Tengo un sueño.', 'Martin Luther King', 'Washington, 1963'],
  ['Sí, se puede.', 'Barack Obama', 'Campaña de 2008, en inglés'],
  ['Sangre, esfuerzo, lágrimas y sudor.', 'Winston Churchill', 'Cámara de los Comunes, 1940'],
  ['Hasta el infinito y más allá.', 'Buzz Lightyear', 'Toy Story, 1995'],
  ['Que la Fuerza te acompañe.', 'Obi-Wan Kenobi', 'Star Wars'],
  ['Sayonara, baby.', 'Terminator', 'Terminator 2, doblaje en España'],
  ['Me llamo Íñigo Montoya. Tú mataste a mi padre. Prepárate a morir.', 'Íñigo Montoya', 'La princesa prometida, 1987'],
  ['Winter is coming. Se acerca el invierno.', 'Ned Stark', 'Juego de tronos'],
  ['¿Qué pasa, neng?', 'El Neng de Castefa', 'Buenafuente, 2005'],
  ['No pasarán.', 'Dolores Ibárruri', 'Discurso en Madrid, 1936'],
  ['Venceréis, pero no convenceréis.', 'Miguel de Unamuno', 'Universidad de Salamanca, 1936'],
  ['Atado y bien atado.', 'Francisco Franco', 'Mensaje de fin de año, 1969'],
  ['OTAN, de entrada no.', 'Felipe González', 'Lema del PSOE en 1982'],
  ['España va bien.', 'José María Aznar', 'Lema de su Gobierno a finales de los noventa'],
  ['¿Quién te ha dicho que quiero que conduzcas por mí?', 'José María Aznar', 'Contra las campañas de la DGT, 2007'],
  ['Lo siento mucho. Me he equivocado y no volverá a ocurrir.', 'Juan Carlos I', 'Tras la cacería de Botsuana, 2012'],
  ['La justicia es igual para todos.', 'Juan Carlos I', 'Mensaje de Navidad, 2011'],
  ['El cielo no se toma por consenso, se toma por asalto.', 'Pablo Iglesias', 'Asamblea de Vistalegre, 2014'],
  ['Comunismo o libertad.', 'Isabel Díaz Ayuso', 'Lema de la campaña de 2021'],
  ['Antes muerta que sencilla.', 'María Isabel', 'Eurovisión Junior, 2004'],
  ['¿Te das cuen?', 'Chiquito de la Calzada', 'Humorista'],
  ['No puedor.', 'Chiquito de la Calzada', 'Humorista'],
  ['¡Cobarde!', 'Chiquito de la Calzada', 'Humorista'],
  ['Salid y disfrutad.', 'Johan Cruyff', 'Antes de la final de Wembley, 1992'],
  ['Jugar al fútbol es muy sencillo, pero jugar un fútbol sencillo es lo más difícil que hay.', 'Johan Cruyff', 'Frase célebre'],
  ['Más que un club.', 'Narcís de Carreras', 'Presidente del Barça, 1968'],
  ['Con la Iglesia hemos topado, Sancho.', 'Don Quijote', 'Cita popular; el original dice «Con la iglesia hemos dado»'],
  ['Vine, vi, vencí.', 'Julio César', 'Batalla de Zela, 47 a. C.'],
  ['La suerte está echada.', 'Julio César', 'Al cruzar el Rubicón, 49 a. C.'],
  ['Dadme un punto de apoyo y moveré el mundo.', 'Arquímedes', 'Siglo III a. C.'],
  ['¡Eureka!', 'Arquímedes', 'Siglo III a. C.'],
  ['Y sin embargo, se mueve.', 'Galileo Galilei', 'Atribuida, 1633'],
  ['El hombre es un lobo para el hombre.', 'Thomas Hobbes', 'De Cive, 1642'],
  ['Dios ha muerto.', 'Friedrich Nietzsche', 'La gaya ciencia, 1882'],
  ['Lo que no me mata me hace más fuerte.', 'Friedrich Nietzsche', 'El ocaso de los ídolos, 1888'],
  ['Proletarios de todos los países, uníos.', 'Karl Marx', 'Manifiesto comunista, 1848'],
  ['La religión es el opio del pueblo.', 'Karl Marx', '1844'],
  ['La imaginación es más importante que el conocimiento.', 'Albert Einstein', 'Entrevista de 1929'],
  ['Ser o no ser, esa es la cuestión.', 'Hamlet', 'Hamlet, de Shakespeare'],
  ['¡Mi reino por un caballo!', 'Ricardo III', 'Ricardo III, de Shakespeare'],
  ['Caminante, no hay camino, se hace camino al andar.', 'Antonio Machado', 'Campos de Castilla, 1912'],
  ['Verde que te quiero verde.', 'Federico García Lorca', 'Romancero gitano, 1928'],
  ['Puedo escribir los versos más tristes esta noche.', 'Pablo Neruda', 'Veinte poemas de amor, 1924'],
  ['Volverán las oscuras golondrinas.', 'Gustavo Adolfo Bécquer', 'Rimas, 1871'],
  ['¿Qué es poesía? Poesía eres tú.', 'Gustavo Adolfo Bécquer', 'Rimas, 1871'],
  ['Y los sueños, sueños son.', 'Segismundo', 'La vida es sueño, de Calderón'],
  ['Muchos años después, frente al pelotón de fusilamiento…', 'Gabriel García Márquez', 'Cien años de soledad, 1967'],
  ['Hasta la victoria siempre.', 'Che Guevara', 'Carta de despedida, 1965'],
  ['Yo soy aquel.', 'Raphael', 'Eurovisión, 1966'],
  ['Volveré.', 'Terminator', 'Terminator, 1984'],
  ['Francamente, querida, me importa un bledo.', 'Rhett Butler', 'Lo que el viento se llevó, 1939'],
  ['Siempre nos quedará París.', 'Rick Blaine', 'Casablanca, 1942'],
  ['Le haré una oferta que no podrá rechazar.', 'Vito Corleone', 'El Padrino, 1972'],
  ['Mi mamá decía: la vida es como una caja de bombones, nunca sabes lo que te va a tocar.', 'Forrest Gump', 'Forrest Gump, 1994'],
  ['Hakuna matata.', 'Timón y Pumba', 'El rey león, 1994'],
  ['Mi tesoro.', 'Gollum', 'El señor de los anillos'],
  ['¡No puedes pasar!', 'Gandalf', 'El señor de los anillos'],
  ['No, yo soy tu padre.', 'Darth Vader', 'El Imperio contraataca, 1980'],
  ['¿Hablas conmigo?', 'Travis Bickle', 'Taxi Driver, 1976'],
  ['Mamá, quiero ser artista.', 'Concha Velasco', 'Musical de 1986'],
  ['Elemental, querido Watson.', 'Sherlock Holmes', 'Cita popular, no textual de Conan Doyle'],
  ['Soy leyenda.', 'Robert Neville', 'Soy leyenda, de Richard Matheson'],
  ['Llámame Ismael.', 'Ismael', 'Moby Dick, de Herman Melville'],
  ['Todos los animales son iguales, pero algunos animales son más iguales que otros.', 'George Orwell', 'Rebelión en la granja, 1945'],
  ['El Gran Hermano te vigila.', 'George Orwell', '1984'],
  ['Lo esencial es invisible a los ojos.', 'El zorro', 'El principito, de Saint-Exupéry']
];
